### ISSUE TITLE
Is there a code version training TadGAN even Orion without primitives?

### ISSUE THREAD

**Issue by Antsypc** [sintel-dev/Orion#269]
It's really inconvenient to write so much json configurations of primitives and pipelines when I try some custom models. 

I write more json than python, and it's hard to debug. I really don't think that is a good way to develop a system and do research.

Sorry for my poor knowledge, I think it's better to develop a set of APIs which is similar to `Sequential` in TensorFlow, stacking layers one by one. Leave more works to users.

Anyways, it's ok to keep primitives json way, but please offer more native python APIs and docs. 

I'm really appreciate your awesome works and could you please explain why you think `primitives` is a good way ? 

Thanks again.

**Comment by Antsypc** [comment]
I have figured out how to code without `mlpipelines` and `mlprimitives`.

I'm sorry. But I keep the idea that `mlblocks` is not a good practice.

I'm really looking forward for your reasons and advices.

**Comment by sarahmish** [comment]
Hi @Antsypc, thank you for your question!

There are many benefits to primitives and pipelines. Here are some aspects that I personally found useful when creating pipelines for Orion:
1. **Reusing primitives**. For a project like Orion, where we have a pipeline hub, we reuse the same code in many pipelines. Primitives is a great way to reduce redundancy.
2. **Validating code**. When primitives are broken down into single operations, we can validating the operating of each primitive and make sure it produces the expected output.
3. **Interpreting pipelines**. One of the cool things about writing pipelines in JSON is that you can easily inspect which primitives are being used and in what sequence.

This is just to list a few, you can read more about MLBazaar in their [paper](https://arxiv.org/pdf/1905.08942.pdf). I also want to point you out to [this notebook](https://github.com/sintel-dev/Orion/blob/master/tutorials/pipelines/lstm_dynamic_threshold.ipynb), because it shows how you can easily go through the primitive inputs and outputs. It is very useful for debugging! There is definitely a learning curve to it, but it's useful once you are familiar with the framework.

Hope this answers your question!
