### ISSUE TITLE
Questions about the experimental results in Table III of the AER paper

### ISSUE THREAD

**Issue by LuYueee** [sintel-dev/Orion#398]
Hello,

I am trying to reproduce the results of this table for the UCR dataset. It would be nice if you could help to verify some experimental details.
![image](https://user-images.githubusercontent.com/32326618/225139815-e0f9a1b2-3a23-47d3-a695-5bb72079295f.png)

1. For the F1 scores in the table, did you call the ‘contextual_f1_score' function that you provide on GitHub [1]? If so, I noticed that this function has 'start', 'end' and 'weighted' parameters, and I was wondering how you set these parameters for the UCR dataset.
contextual_f1_score(ground_truth, anomalies, start=start, end=end, weighted=False)
[1] https://github.com/sintel-dev/Orion/tree/master/orion/evaluation#contextual-scoring

2. Regarding the F1 scores on the table.
Since the UCR dataset contains 250 datasets, did you calculate the F1 score for each dataset and then average it?

3. Here is a case where the F1 score cannot be defined - 
If the predicted result and the ground truth do not have any intersection, at this point TP = 0, so the precision and recall are both 0. It will result in a divide-by-0 error when calculating the F1 score. How to define F1 in this case?
![image](https://user-images.githubusercontent.com/32326618/225139889-f5ed648f-8a3f-40e1-b6a6-1ed587f14e72.png)
![image](https://user-images.githubusercontent.com/32326618/225139905-3a7d3d73-2a9a-4bd7-907c-e108905e710b.png)

Thank you,
Yue Lu

**Comment by sarahmish** [comment]
Hi @LuYueee , thank you for opening an issue!

1. Yes, we use `contextual` type of scoring, specifically overlapping segment. You can compute the f1 score, for example, with this function `contextual_f1_score(ground_truth, predicted_anomalies, data=test, weighted=False)`.
2. The exact calculation of the F1 score is provided in https://github.com/sintel-dev/Orion/blob/master/orion/results.py. We actually compute the total true positives, false positives, and false negatives per dataset and compute the f1 score, rather than averaging it (because of reason in 3).
3. Yes, there are cases when the f1 score is undefined, and in this case, we consider that we missed all the anomalies (false negative = # missed anomalies). Then we compute the total f1 score according to 2.

Let me know if you have any further questions!
