### ISSUE TITLE
Questions about the uncertainty of prediction results.

### ISSUE THREAD

**Issue by Jorvy-ZZW** [sintel-dev/Orion#399]
Hi!
            Reliability analysis of test results is often required for abnormal detection in fields with high requirements on equipment safety, such as nuclear power and aviation engines. Could you please tell me how to quantify the uncertainty of prediction results?

**Comment by sarahmish** [comment]
Hi @Jorvy-ZZW, thank you for using Orion!

You can use the `severity` value as a measure of how likely the interval is of being anomalous. The higher the value the more anomalous.

I want to touch on the idea of uncertainty. Because all pipelines in Orion are unsupervised, it is hard to get a real measure of uncertainty (or confidence). The model has no observation to the real anomalous data and therefore uncertainty cannot be computed.
